/* tslint:disable */
/* eslint-disable */

import { mapValues } from '../runtime';
/**
 * ### Risk Level Determination
 * This documentation outlines how the risk level is determined based on a `normalizedScore` generated by a **multivariate linear regression model**. The risk level provides a static representation of thresholds to classify the severity of risk for an entity.
 * 
 * ---
 * 
 * > **IMPORTANT:** 
 * > The risk report model is not available in the free plan. To access this feature, you need to subscribe to a paid plan.
 * 
 * ---
 * 
 * #### How the Score is Generated
 * 
 * The risk score (`normalizedScore`) is computed using a **multivariate linear regression model**, a machine learning approach that evaluates multiple input features to predict the risk score.
 * 
 * ##### Key Features of the Model:
 * 1. **Dynamic Scoring:** The model assigns weights to various risk factors, dynamically updating them based on training with new data.
 * 2. **Constant Training:** The model is continuously retrained with the latest data to improve accuracy and adapt to evolving risk patterns.
 * 3. **Scalability:** The model supports multiple features and their interactions, deriving a comprehensive and reliable risk score.
 * 
 * The output score is normalized to a range of **200–1000** for easier interpretation and alignment with industry practices.
 * 
 * ---
 * 
 * #### Risk Level Thresholds
 * 
 * The risk level is a static representation of the `normalizedScore`, categorized into five distinct levels:
 * 
 * | **Risk Level** | **Score Range**          | **Description**                                                                 |
 * |----------------|--------------------------|---------------------------------------------------------------------------------|
 * | `highest`      | `normalizedScore > 800` | Represents the most critical level of risk. Immediate attention is required.   |
 * | `high`         | `600 < normalizedScore <= 800` | Indicates a high level of risk. Consider mitigation actions promptly.          |
 * | `medium`       | `400 < normalizedScore <= 600` | Reflects a moderate level of risk. Monitoring and possible action advised.     |
 * | `low`          | `300 < normalizedScore <= 400` | Denotes a low level of risk. Regular monitoring is sufficient.                 |
 * | `lowest`       | `normalizedScore <= 300` | The lowest level of risk. Risk is considered negligible or minimal.            |
 * 
 * ---
 * 
 * #### Usage
 * 
 * This risk level determination serves as a human-readable representation of the machine learning model's output. It enables:
 * - **Risk Monitoring:** Identifying entities that require immediate attention.
 * - **Action Prioritization:** Guiding mitigation efforts based on the severity of the risk.
 * - **Decision-Making:** Providing clear thresholds for automated and manual workflows.
 * 
 * ---
 * 
 * #### Key Notes
 * 1. **Dynamic Scoring, Static Levels:**
 *   - While the score is dynamically updated through a multivariate linear regression model, the risk levels remain static to maintain consistency and interpretability.
 * 
 * 2. **Customizable Thresholds:**
 *   - The thresholds for the levels are configurable based on organizational needs or domain-specific requirements.
 * 
 * 3. **Model Retraining:** 
 *   - Regular updates to the model ensure that scores accurately reflect real-world risk trends, improving the reliability of level assignments.
 * 
 * ---
 * 
 * This approach combines the adaptability of multivariate linear regression with the simplicity of static thresholds, offering a robust framework for risk assessment and decision-making.
 * 
 * ---
 * 
 * ### Response Elements
 * 
 * @export
 * @interface RiskReport
 */
export interface RiskReport {
    /**
     * Risk score normalized to a range of 200–1000.
     * @type {number}
     * @memberof RiskReport
     */
    score?: number;
    /**
     * Static representation of the risk level.
     * @type {string}
     * @memberof RiskReport
     */
    level?: string;
}

/**
 * Check if a given object implements the RiskReport interface.
 */
export function instanceOfRiskReport(value: object): value is RiskReport {
    return true;
}

export function RiskReportFromJSON(json: any): RiskReport {
    return RiskReportFromJSONTyped(json, false);
}

export function RiskReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskReport {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : json['score'],
        'level': json['level'] == null ? undefined : json['level'],
    };
}

export function RiskReportToJSON(json: any): RiskReport {
    return RiskReportToJSONTyped(json, false);
}

export function RiskReportToJSONTyped(value?: RiskReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
        'level': value['level'],
    };
}

