/* tslint:disable */
/* eslint-disable */

import { mapValues } from '../runtime';
/**
 * This documentation outlines how the risk report is determined based on a `normalizedScore` generated by analyzing multiple email-related parameters against predefined risk factors (`baseAnalysis`).…
 * @export
 * @interface RiskReportEmail
 */
export interface RiskReportEmail {
    /**
     * Risk score normalized and clamped to the 200–1000 range.
     * @type {number}
     * @memberof RiskReportEmail
     */
    score?: number;
    /**
     * Static representation of the risk level bucket aligned to the score range. Allowed values: `highest`, `high`, `medium`, `low`, `lowest`. Example: `highest`.
     * @type {string}
     * @memberof RiskReportEmail
     */
    level?: string;
    /**
     * Provide the breakdown of the highest-weight risk factors used in the analysis. Additional lower-weight signals may exist outside this array.
     * @type {Array<string>}
     * @memberof RiskReportEmail
     */
    baseAnalysis?: Array<string>;
}

/**
 * Check if a given object implements the RiskReportEmail interface.
 */
export function instanceOfRiskReportEmail(value: object): value is RiskReportEmail {
    return true;
}

export function RiskReportEmailFromJSON(json: any): RiskReportEmail {
    return RiskReportEmailFromJSONTyped(json, false);
}

export function RiskReportEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskReportEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : json['score'],
        'level': json['level'] == null ? undefined : json['level'],
        'baseAnalysis': json['baseAnalysis'] == null ? undefined : json['baseAnalysis'],
    };
}

export function RiskReportEmailToJSON(json: any): RiskReportEmail {
    return RiskReportEmailToJSONTyped(json, false);
}

export function RiskReportEmailToJSONTyped(value?: RiskReportEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
        'level': value['level'],
        'baseAnalysis': value['baseAnalysis'],
    };
}

