/* tslint:disable */
/* eslint-disable */

import { mapValues } from '../runtime';
/**
 * This documentation outlines how the risk level is determined based on a `normalizedScore` generated by a **multivariate linear regression model**. The risk level provides a static representation of…
 * @export
 * @interface RiskReportIp
 */
export interface RiskReportIp {
    /**
     * Risk score normalized to a range of 200–1000.
     * @type {number}
     * @memberof RiskReportIp
     */
    score?: number;
    /**
     * Static representation of the risk level.
     * @type {string}
     * @memberof RiskReportIp
     */
    level?: string;
    /**
     * Provide the breakdown of the highest-weight risk factors used in the analysis. Additional lower-weight signals may exist outside this array.
     * @type {Array<string>}
     * @memberof RiskReportIp
     */
    baseAnalysis?: Array<string>;
}

/**
 * Check if a given object implements the RiskReportIp interface.
 */
export function instanceOfRiskReportIp(value: object): value is RiskReportIp {
    return true;
}

export function RiskReportIpFromJSON(json: any): RiskReportIp {
    return RiskReportIpFromJSONTyped(json, false);
}

export function RiskReportIpFromJSONTyped(json: any, ignoreDiscriminator: boolean): RiskReportIp {
    if (json == null) {
        return json;
    }
    return {
        
        'score': json['score'] == null ? undefined : json['score'],
        'level': json['level'] == null ? undefined : json['level'],
        'baseAnalysis': json['baseAnalysis'] == null ? undefined : json['baseAnalysis'],
    };
}

export function RiskReportIpToJSON(json: any): RiskReportIp {
    return RiskReportIpToJSONTyped(json, false);
}

export function RiskReportIpToJSONTyped(value?: RiskReportIp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'score': value['score'],
        'level': value['level'],
        'baseAnalysis': value['baseAnalysis'],
    };
}

